add_newline = false

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[java]
disabled = true

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
# untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "!"
staged = "++"
# renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

