add_newline = false

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[java]
disabled = true

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
# untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
# modified = "ğŸ“"
staged.value = "++"
staged.enabled = true
staged.style = "green"
modified.enabled = true
# renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

