add_newline = false

[java]
disabled = true

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
# untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
# modified = "ğŸ“"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
modified_count.enabled = true
staged_count.style = "green"
# renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
